testi13.12/Models/EläimiäContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;


namespace testi13._12.Models {
         
    public partial class EläimiäContext : DbContext
    { 
    
    public EläimiäContext()
    {
    }

    public EläimiäContext(DbContextOptions<EläimiäContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Eläinlääkärit> Eläinlääkärit { get; set; }
    public virtual DbSet<Omistajat> Omistajat { get; set; }
    public virtual DbSet<Potilastiedot> Potilastiedot { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=localhost\\SQLEXPRESS;Database=Eläimiä;Trusted_Connection=True;");
        }
    }
    

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Eläinlääkärit>(entity =>
            {
               entity.HasKey(e => e.Ideläinlääkäri);

                entity.Property(e => e.Ideläinlääkäri)
                    .HasColumnName("IDEläinlääkäri")
                    .ValueGeneratedNever();

                entity.Property(e => e.Etunimi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Osoite)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Puhelinnumero)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Sukunimi)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Omistajat>(entity =>
            {
                entity.HasKey(e => e.Idomistaja);

                entity.Property(e => e.Idomistaja)
                    .HasColumnName("IDOmistaja")
                    .ValueGeneratedNever();

                entity.Property(e => e.Etunimi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Osoite)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Puhelinnumero)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Sukunimi)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Potilastiedot>(entity =>
            {
                entity.HasKey(e => e.Idasiakas);

                entity.Property(e => e.Idasiakas)
                    .HasColumnName("IDAsiakas")
                    .ValueGeneratedNever();

                entity.Property(e => e.Ideläinlääkäri).HasColumnName("IDEläinlääkäri");

                entity.Property(e => e.Idomistaja).HasColumnName("IDOmistaja");

                entity.Property(e => e.Laji)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Nimi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Rotu)
                    .HasMaxLength(50)
                    .IsUnicode(false);

            });


        }
    }

}

testi13.12/Models/Eläinlääkärit.cs
using System;
using System.Collections.Generic;

namespace testi13._12.Models
{
    public partial class Eläinlääkärit
    {
        public int Ideläinlääkäri { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Osoite { get; set; }
        public string Puhelinnumero { get; set; }
    }
}

testi13.12/Models/ErrorViewModel.cs
using System;

namespace testi13._12.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

testi13.12/Models/Omistajat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace testi13._12.Models
{
    public partial class Omistajat
    {
        public int Idomistaja { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Osoite { get; set; }
        public string Puhelinnumero { get; set; }
    }
}

testi13.12/Models/Potilastiedot.cs
using System;
using System.Collections.Generic;

namespace testi13._12.Models
{
    public partial class Potilastiedot
    {
        public int Idasiakas { get; set; }
        public string Nimi { get; set; }
        public string Laji { get; set; }
        public string Rotu { get; set; }
        public int? Idomistaja { get; set; }
        public int? Ideläinlääkäri { get; set; }
    }
}

testi13.12/Controllers/EläinlääkäritController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using testi13._12.Models;

namespace testi13._12.Controllers
{
    public class EläinlääkäritController : Controller
    {
        public IActionResult Index()
        {
            EläimiäContext context = new EläimiäContext();
            List<Eläinlääkärit> eläinlääkäri = context.Eläinlääkärit.ToList();
            return View(eläinlääkäri);
        }
        public IActionResult UusiEläinlääkäri()
        {
            return View();

        }
        [HttpPost]
        public IActionResult UusiEläinlääkäri(Eläinlääkärit uusi)
        {
            EläimiäContext context = new EläimiäContext();
            context.Eläinlääkärit.Add(uusi);
            context.SaveChanges();
            return View();

        }

    }


}

testi13.12/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using testi13._12.Models;

namespace testi13._12.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

testi13.12/Controllers/OmistajatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using testi13._12.Models;

namespace testi13._12.Controllers
{
    public class OmistajatController : Controller
    {
        public IActionResult Index()
        {
            EläimiäContext context = new EläimiäContext();
            List<Omistajat> omistaja = context.Omistajat.ToList();
            return View(omistaja);
        }
        public IActionResult UusiOmistaja()
        {
            return View();
        
        }
        [HttpPost]
        public IActionResult UusiOmistaja(Omistajat uusi)
        {
            EläimiäContext context = new EläimiäContext();
            context.Omistajat.Add(uusi);
            context.SaveChanges();
            return View();

        }

    }
}

testi13.12/Controllers/PotilastiedotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using testi13._12.Models;

namespace testi13._12.Controllers
{
    public class PotilastiedotController : Controller
    {
        public IActionResult Index()
        {
            EläimiäContext context = new EläimiäContext();
            List<Potilastiedot> potilastiedot = context.Potilastiedot.ToList();
            return View(potilastiedot);
        }
        public IActionResult UusiPotilastieto()
        {
            return View();

        }
        [HttpPost]
        public IActionResult UusiPotilastieto(Potilastiedot uusi)
        {
            EläimiäContext context = new EläimiäContext();
            context.Potilastiedot.Add(uusi);
            context.SaveChanges();
            return View();

        }

    }

   
}

testi13.12/Views/Eläinlääkärit/Index.cshtml
@model IEnumerable<testi13._12.Models.Eläinlääkärit>
@{
    ViewData["Title"] = "Index";
}

<h2>Eläinlääkärit-tietokanta</h2>


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ideläinlääkäri)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Etunimi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sukunimi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Osoite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puhelinnumero)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ideläinlääkäri)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Etunimi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sukunimi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Osoite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Puhelinnumero)
                </td>

               
            </tr>
        }
    </tbody>
</table>

testi13.12/Views/Eläinlääkärit/UusiEläinlääkäri.cshtml
@model testi13._12.Models.Eläinlääkärit

@{
    ViewData["Title"] = "UusiEläinlääkäri";
}

<h2>UusiEläinlääkäri</h2>

<h4>Eläinlääkärit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UusiEläinlääkäri">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ideläinlääkäri" class="control-label"></label>
                <input asp-for="Ideläinlääkäri" class="form-control" />
                <span asp-validation-for="Ideläinlääkäri" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etunimi" class="control-label"></label>
                <input asp-for="Etunimi" class="form-control" />
                <span asp-validation-for="Etunimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sukunimi" class="control-label"></label>
                <input asp-for="Sukunimi" class="form-control" />
                <span asp-validation-for="Sukunimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Osoite" class="control-label"></label>
                <input asp-for="Osoite" class="form-control" />
                <span asp-validation-for="Osoite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puhelinnumero" class="control-label"></label>
                <input asp-for="Puhelinnumero" class="form-control" />
                <span asp-validation-for="Puhelinnumero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

testi13.12/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Toiminnot";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData[""]</h3>


<p>
    <ul>

        <li> <a href="https://localhost:44343/potilastiedot/uusipotilastieto">Lisää uusi potilas</a> </li>

        <li> <a href="https://localhost:44343/Omistajat/">Omistajatietokanta</a> </li>

        <li>  <a href="https://localhost:44343/Omistajat/Uusiomistaja">Lisää uusi omistaja</a> </li>

        <li>  <a href="https://localhost:44343/eläinlääkärit">Eläinlääkäritietokanta</a> </li>

        <li>    <a href="https://localhost:44343/eläinlääkärit/uusieläinlääkäri">Lisää uusi eläinlääkäri</a> </li>


    </ul>
</p>

testi13.12/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Yhteystiedot";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData[""]</h3>

<address>
    Iloinen eläinlääkäriasema<br />
    Joensuu,  98052-6399<br />
    <abbr title="Puhelin">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

testi13.12/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<body>

    <h1 style="font-size:60px;">Iloinen eläinlääkäriasema</h1>

    <p>Laadukasta ja iloista eläinlääkäripalvelua kissallesi.</p>






</body>

</html>

testi13.12/Views/Omistajat/Index.cshtml
@model IEnumerable< testi13._12.Models.Omistajat>
@{
        ViewData["Title"] = "Index";
    }

<h2>Omistajatietokanta</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Idomistaja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Etunimi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sukunimi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Osoite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puhelinnumero)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
{
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Idomistaja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Etunimi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sukunimi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Osoite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Puhelinnumero)
                </td>
             
               
            </tr>
        }
    </tbody>
</table>

testi13.12/Views/Omistajat/UusiOmistaja.cshtml
@model testi13._12.Models.Omistajat

@{
    ViewData["Title"] = "UusiOmistaja";
}

<h2>Lisää uusi omistaja</h2>

<h4>Omistajat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UusiOmistaja">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Idomistaja" class="control-label"></label>
                <input asp-for="Idomistaja" class="form-control" />
                <span asp-validation-for="Idomistaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etunimi" class="control-label"></label>
                <input asp-for="Etunimi" class="form-control" />
                <span asp-validation-for="Etunimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sukunimi" class="control-label"></label>
                <input asp-for="Sukunimi" class="form-control" />
                <span asp-validation-for="Sukunimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Osoite" class="control-label"></label>
                <input asp-for="Osoite" class="form-control" />
                <span asp-validation-for="Osoite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puhelinnumero" class="control-label"></label>
                <input asp-for="Puhelinnumero" class="form-control" />
                <span asp-validation-for="Puhelinnumero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

testi13.12/Views/Potilastiedot/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

testi13.12/Views/Potilastiedot/UusiPotilastieto.cshtml
@model testi13._12.Models.Potilastiedot

@{
    ViewData["Title"] = "UusiOmistaja";
}

<h2>Lisää uusi eläinpotilas</h2>

<h4>Potilastiedot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UusiOmistaja">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Idasiakas" class="control-label"></label>
                <input asp-for="Idasiakas" class="form-control" />
                <span asp-validation-for="Idasiakas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nimi" class="control-label"></label>
                <input asp-for="Nimi" class="form-control" />
                <span asp-validation-for="Nimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Laji" class="control-label"></label>
                <input asp-for="Laji" class="form-control" />
                <span asp-validation-for="Laji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rotu" class="control-label"></label>
                <input asp-for="Rotu" class="form-control" />
                <span asp-validation-for="Rotu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idomistaja" class="control-label"></label>
                <input asp-for="Idomistaja" class="form-control" />
                <span asp-validation-for="Idomistaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ideläinlääkäri" class="control-label"></label>
                <input asp-for="Ideläinlääkäri" class="form-control" />
                <span asp-validation-for="Ideläinlääkäri" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

testi13.12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - testi13._12</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Iloinen eläinlääkäriasema</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Etusivu</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Toiminnot</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Yhteystiedot</a></li>
                    <li><a asp-area="" asp-controller="Eläinlääkärit" asp-action="Index">Eläinlääkärit</a></li>
                    <li><a asp-area="" asp-controller="Eläinlääkärit" asp-action="UusiEläinlääkäri">Eläinlääkärin lisäys</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Iloinen eläinlääkäriasema 2019 Soile N.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>